
apiVersion: apps/v1


kind: Deployment

metadata:
  name: probe-cs-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      run: probe-cs-demo

  template:
    metadata:
      labels:
        run: probe-cs-demo

    spec:
      containers:
      - name: probe-cs-demo
        image: tma-monitor/probe-cs-demo:0.1
        tty: true

