
apiVersion: apps/v1


kind: Deployment

metadata:
  name: probe-k8s-docker

spec:
  replicas: 1
  selector:
    matchLabels:
      run: probe-k8s-docker

  template:
    metadata:
      labels:
        run: probe-k8s-docker

    spec:
      containers:
      - name: probe-k8s-docker
        image: tma-monitor/probe-k8s-docker:0.1
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        tty: true
        ports:
        - containerPort: 5000
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock

