apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    name: web
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus # has to match .spec.template.metadata.labels
  serviceName: "prometheus"
  template:
    metadata:
      labels:
        app: prometheus # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: prometheus
        image: prometheus:0.1
        ports:
        - containerPort: 9090
