apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kubernetes/Desktop/volumes_kafka
