
apiVersion: apps/v1


kind: Deployment

metadata:
  name: probe-k8s-metrics-server

spec:
  replicas: 1
  selector:
    matchLabels:
      run: probe-k8s-metrics-server

  template:
    metadata:
      labels:
        run: probe-k8s-metrics-server

    spec:
      containers:
      - name: probe-k8s-metrics-server
        image: tma-monitor/probe-k8s-metrics-server:0.1
        tty: true

